### ISSUE TITLE
Please find a better solution for this ;)

### ISSUE THREAD

**Issue by ddigulescu** [TraianBrb/iQuest-Css-Session#1]
https://github.com/TraianBrb/iQuest-Css-Session/blob/2472ee214444a6fdafa3313f84b4b50cabfe1d6e/source/scss/styles.scss#L298

It's ok but if I change the `font-size`: https://drive.google.com/open?id=1CdPUCifRhDHRZfxJlWV-hiECrLyS98aI
maybe:
```
li {
    @include emify(background-size, 10px);
    padding-left: 18px;
   &:before {
   ...
   }
}
```
Anyway, nice job! 👍

**Comment by TraianBrb** [comment]
I replaced the background-image with FontAwesome icon 

```
li.ingredients-list__item {
  @include emify(background-size, 10px);
  padding-left: 18px;
  line-height: 1.5;
  &:before {
    font-family: FontAwesome;
    color: $content-red;
    content: "\f101";
    padding-right: 8px;
  }
}
```
Now the list arrows are centered and crisp at any ```font-size```.

Thank you!
